name: Lint

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/shellcheck-action@master
        with:
          scandir: './bin'
          additional_files: './lib/aliases.sh'
          severity: warning
